version: '2.2'
services:
  elasticsearch01:
    build: es
    container_name: elasticsearch01
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    ports:
      - 9201:9200
    networks:
      - esnet

  elasticsearch02:
    build: es
    container_name: elasticsearch02
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    ports:
      - 9202:9200
    networks:
      - esnet

  kibana01:
    build: kibana
    container_name: kibana01
    links:
      - elasticsearch01:elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
